### ISSUE TITLE
dazzle migrate crashes: EntitySpec.relations and FieldSpec.unique API mismatches

### ISSUE THREAD

**Issue by manwithacat** [manwithacat/dazzle#616]
## Problem

`dazzle migrate` crashes on post-v0.45.0 main (commit `1ae93554`) with two API mismatches between `dazzle.core` and `dazzle_back.runtime`:

### 1. `EntitySpec` has no `relations` attribute

```
File "/Volumes/SSD/Dazzle/src/dazzle_back/runtime/relation_loader.py", line 88
  for rel in entity.relations:
AttributeError: 'EntitySpec' object has no attribute 'relations'
```

`RelationRegistry.from_entities()` expects `entity.relations` but `EntitySpec` uses `fields` with `ref` type instead. The migration planner calls this at line 167 of `migrations.py`.

### 2. `FieldSpec` has no `unique` attribute (it's `is_unique`)

```
File "/Volumes/SSD/Dazzle/src/dazzle_back/runtime/sa_schema.py", line 156
  if field.unique:
AttributeError: 'FieldSpec' object has no attribute 'unique'. Did you mean: 'is_unique'?
```

`build_metadata()` accesses `field.unique` but `FieldSpec` uses `is_unique`.

### Reproduction

```bash
cd /Volumes/SSD/pennydreadful  # any project with entities
DATABASE_URL="postgresql://localhost:5432/penny_dreadful" dazzle migrate --dry-run
```

### Impact

`dazzle migrate` is completely non-functional on post-v0.45.0 main. Workaround: create tables manually via SQL.

### Environment

- Dazzle: v0.45.0 (commit `1ae93554`, editable install)
- Python: 3.12.11
- Platform: Darwin arm64

**Comment by manwithacat** [comment]
Fixed in latest commit. Two API mismatches:
- `entity.relations` → `getattr(entity, 'relations', [])` (EntitySpec uses .fields with ref type)
- `field.unique` → `getattr(field, 'is_unique', False)` (FieldSpec uses is_unique property)

`dazzle migrate` should now work on post-v0.45.0.
